"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_yellow)\
$username\
$hostname\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$nix_shell\
[](fg:color_bg3 bg:color_context)\
$kubernetes\
[](fg:color_context bg:color_bg1)\
$jobs\
$status\
[ ](fg:color_bg1)\
$line_break$character"""

right_format = """$cmd_duration$time"""

palette = 'gruvbox_dark_hard'

[palettes.gruvbox_dark_hard]
color_fg0 = '#ebdbb2'
color_fg1 = '#fbf1c7'
color_bg1 = '#282828'
color_bg3 = '#504945'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_context = '#7c6f64'
color_red = '#cc241d'
color_yellow = '#d79921'
color_gray = '#928374'
color_bg_dim = '#1d2021'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.gruvbox_material_medium]
color_fg0 = '#d4be98'
color_fg1 = '#ddc7a1'
color_bg1 = '#32302f'
color_bg3 = '#45403d'
color_blue = '#7daea3'
color_aqua = '#89b482'
color_green = '#a9b665'
color_orange = '#e78a4e'
color_purple = '#d3869b'
color_red = '#ea6962'
color_yellow = '#d8a657'
color_gray = '#7c6f64'
color_bg_dim = '#1b1b1b'

[os]
disabled = true
style = "bg:color_orange fg:color_bg_dim"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = false
style_user = "bg:color_yellow fg:color_bg_dim"
style_root = "bg:color_yellow fg:color_red"
format = '[ $user ]($style)'

[hostname]
ssh_only = true
style = "bg:color_yellow fg:color_bg_dim"
format = '[@$hostname ]($style)'

[directory]
style = "fg:color_bg_dim bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_bg_dim bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind)](fg:color_bg_dim bg:color_aqua)]($style)'
modified = '~ '
ahead = '↑${count} '
behind = '↓${count} '
diverged = '↕↑${ahead_count}↓${behind_count} '
renamed = '» '
staged = '+ '


[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol $virtualenv ](fg:color_bg_dim bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[nix_shell]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol $state( $name) ](fg:color_blue bg:color_bg3)]($style)'

[kubernetes]
disabled = false
symbol = "󱃾"
style = "bg:color_context"
format = '[[ $symbol $context(::$namespace) ](fg:color_bg_dim bg:color_context)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:color_bg1"
format = '[[ 󱎫 $duration ](fg:color_yellow bg:color_bg1)]($style)'

[jobs]
style = "bg:color_bg1"
format = '[[ $symbol$number ](fg:color_aqua bg:color_bg1)]($style)'

[status]
disabled = false
style = "bg:color_bg1"
symbol = "✘"
format = '[[ $symbol $status ](fg:color_red bg:color_bg1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](fg:color_green)'
error_symbol = '[](fg:color_red)'
vimcmd_symbol = '[](fg:color_green)'
vimcmd_replace_one_symbol = '[](fg:color_purple)'
vimcmd_replace_symbol = '[](fg:color_purple)'
vimcmd_visual_symbol = '[](fg:color_yellow)'
